### ISSUE TITLE
development with stack

### ISSUE THREAD

**Issue by meditans** [music-suite/music-suite#14] opened 2016-02-16 20:03 UTC
Hi, I briefly tinkered with the music suite again, and I noticed that the current multi-repo structure on github is a bit clumsy as far as stack workflow goes: basically to play with the suite you have to understand which repos are useful in the music-suite project, clone all in separate folder, and then manually creating the `stack.yaml` files required.

There is an alternative, which is organizing the music suite in one big repo (a top-folder which contains each one of the music-\* folder). This has the advantage that you can start hacking with `git clone repo` and `stack build`.

If you're open in exploring this route, we could talk more on the benefits of this solution, but I think the main feature is lowering the contribution barrier. I realize that there could be some migration cost regarding the git history of the repos, so I'm interested in your opinion on the matter.

**Comment by meditans** [comment] 2016-02-18 15:55
As an alternative, with which I experimented in these days, we could insert in the `readme` a command to automatically clone all the develoment repos, and add a `stack.yaml` file (in a gist, maybe) to use in the superior directory.

This would have the advantage of not requiring a modification to the github project, so I think it's better than the previous suggestion.

**Comment by hanshoglund** [comment] 2016-02-28 02:08
Hi Carlo,

What if we simply put the Stack file in this repo and used `../music-pitch` etc? Arguably stack should not build stuff outside the repo since that makes it non-reproducible, but as all packages are cross-versioned at least the releases should be OK.

**Comment by meditans** [comment] 2016-02-29 21:34
Hi, 
I think the objective here is to make easier for an user to:

- clone the project in a form that permits coherent modification to all subpackages.
- edit with the tools he's familiar with.
- use his entire modified `music suite` in his other projects, without necessarily having to wait for a release.
- contribute upstream.

So in the next part, I'll use as an example a user which is interested in working on the `music-articulation` package, with the requisites listed above.

If I understood correctly, you're proposing to put the `stack.yaml` file in the `music-suite` repository. The problem with this is that some of our user's tools, like `ghc-mod` won't work in this stack setup when he's working on `music-articulation`. In fact the tools won't recognize `music-articulation` as a stack project directory, because there isn't a `stack.yaml` in that folder nor in a superior directory (and by default haskell mode will try to build that with cabal, causing problems). So our user will follow the path of least resistance and add the stack.yaml file by himself. This is completely avoidable when we can just supply one super file for all projects.

So here it's the proposed work-flow, we provide both:

- a shell script to clone all the repositories which compose the music-suite. This automates a process that the user will have to do by himself in every case.
- a global stack yaml file, to be sure to offer first-class tool support to all sub-packages.

The overall structure should be something like:

    music
    - music-suite
    - music-articulation
    - ...
    - stack.yaml
    - cloneAll.sh

(a more refined alternative would be to use git submodules). In case you're ok with this and decide for an appropriate location, I can already provide the scripts and the stack.yaml file.

**Comment by hanshoglund** [comment] 2016-02-29 23:46
I'm fine with moving the stack file to a location compatible with ghc-mod.

I originally wrote [music-util](https://github.com/music-suite/music-util) for managing these kind of things. It is essentially a fancy shell script written in Haskell and actually has a [clone command](https://github.com/music-suite/music-util/blob/master/src/music-util.hs#L289), however it then proceeds to setup a Cabal sandboxes structure (it predated Stack), which should be removed.

I think the right thing to do would be to modify the music-util script as follows:
 
- Remove/deprecate it as a package, as that gives you the impression that it is one of the packages in the suite, which was never the case.
- Make it work as a stack script by [adding these lines](http://docs.haskellstack.org/en/stable/GUIDE/#script-interpreter)
- Remove all the sandbox related stuff
- Make it download the stack file from somewhere if it doesn’t exist and (optionally) invoke `stack setup` (replacing `sandbox init`).

The recommended way to ”get started hacking” would then be simply:
- Install Stack
- Run `./music-util.hs setup` (or `stack music-util.hs setup`)

Done, ready to invoke `stack build music-suite`.

Re: submodules I think that's overkill at this point, as we only want to make sure that the master HEADS and releases build together. To get truly reproducible builds (i.e for releases) I think [using commit IDs in the stack file](http://docs.haskellstack.org/en/stable/yaml_configuration/#project-config) would be better than submodules in any case.

**Comment by meditans** [comment] 2016-03-01 00:19
Oh, I never realized that was the purpose of `music-util`. I'm taking a look at the script now, and I'm just gonna ask the stupid question: what is the script approach buying us over a simple script like [this](https://gist.github.com/e5fa3204ecca360d2231)?

In the meantime I'll read it more carefully!

**Comment by meditans** [comment] 2016-03-01 00:37
Ok, so I see the other purpose of `music-util` is building the docs for the site, that's actually useful, but I think that should be a different thing from "how to clone and hack the project"

There is also quite a lot of code on platform compatibility: why is that? What does path manipulation like `$MUSIC_SUITE_DIR` accomplish here?

**Comment by hanshoglund** [comment] 2016-03-01 01:12
Essentially music-util is collection of utility stuff, which could absolutely be split into separate scripts.
- I use foreach a lot, i.e. `music-util foreach git status` to make sure I haven't forgotten to commit in some directory, and `music-util foreach tag v1.2.3` for releases, cabal uploads etc.
- The getPackagePath is used to find the path where GHC/Cabal generates the package DB, which should be passed to GHCI or programs invoking music-suite using the GHC API (including the code that generates the docs and the test suite). For example ```GHC_PACKAGE_PATH=`music-util package-path` ghci```.
- The sandbox management stuff is not needed anymore as Stack takes care of this for us

**Comment by meditans** [comment] 2016-03-01 01:21
Foreach seems useful, indeed, a more secure version of:

    for i in `ls`; do cd $i && git status && cd ..; done

Regarding the path, would you say that one of the outputs of `stack path` facilitates this use case?

What are you suggestions for the setting up script? Is a simple bash script like the one I linked before an option or should we focus on a more integrated solution in the spirit of `music-util`?

**Comment by hanshoglund** [comment] 2016-03-01 19:09
As I said I think `music-util` has its uses, but to just get people started a simple script would definitely work just as well. A nice thing about unifying them would of course be that everybody who uses the download script get the utilities automatically, but this does not feel like a high-prio.

I appreciate your efforts to lower the barrier to the libraries, I have actually thought for some time about doing just that to push the libraries into higher adoption (fixing bugs and speed issues, particularly in the import/export code should probably help as well!).

**Comment by hanshoglund** [comment] 2016-03-05 17:19
Copied from chat:

> hanshoglund Mar 02 15:19
Re: script/yaml: while the stack.yaml would naturally go inside a gist, unfortunately we can't really do organization-owned gists. What about 1) putting both music-suite/music-suite/scripts 2) make the setup script actually download the stack file using wget or whatever if it's written in haskell 3) Write README/dev docs that instructs new hackers to just A) install stack B) download and run the script (giving them the correct repos and stack file).

**Comment by hanshoglund** [comment] 2016-03-05 17:20
I put up the stack file I currently use here as a temporary measure:
https://github.com/music-suite/music-suite/wiki/Stack-file-(temporary)

**Comment by povman** [comment] 2016-12-31 05:43
FWIW I just got music-suite to build using these steps:

1. mkdir ~/music-suite-main
2. cd ~/music-suite-main
3. export MUSIC_SUITE_DIR=$PWD
4. Unzip this file there: [music-files.zip](https://github.com/music-suite/music-suite/files/679487/music-files.zip) (Containing slightly updated versions of music-util.hs and stack.yaml)
5. stack music-util.hs setup clone
6. stack setup
7. stack build

**Comment by hanshoglund** [comment] 2020-04-28 17:58
This should now work with Nix+Cabal (instructions in the README). I'm not against supporting Stack if somebody would like to attempt a port!

Will close this as out-of-date.

**Closed by hanshoglund** 2020-04-28 17:58 UTC

**Comment by jwaldmann** [comment] 2020-09-24 19:40
see also https://github.com/jwaldmann/music-suite/blob/master/stack.yaml
